[pytest]
python_files = test_*.py
python_functions = test_*
python_classes = Test*

addopts =
    -v
    --headed --slowmo 1000 
    --html=reports/report.html
    --self-contained-html
   # --browser chromium
   #--browser firefox
   # --browser webkit

testpaths =
    tests